Deployment keys
YaaS/docpad-skeleton-apidocs pull request #36
Opened 2017-04-13 13:15 UTC by alan-hadyk

2017-04-19 12:28 UTC, przezor commented on gulpFunctions.js
> +  chewie.preparePushResult(config, opt, (err) => {
I guest that it is not necessary?

2017-04-19 12:28 UTC, przezor requested changes

2017-04-19 12:28 UTC, przezor commented on gulpFunctions.js
> +    /TO_REPLACE_REDIR_URL=[^,]*/,
What are these changes? :O

2017-04-19 12:28 UTC, przezor commented on .gitignore
> +deploy-key
I guess that should not be here?

2017-04-19 12:30 UTC, przezor commented on .travis.yml
> +- openssl aes-256-cbc -K $encrypted_321fb9daba18_key -iv $encrypted_321fb9daba18_iv -in deploy-key.enc -out deploy-key -d
i would say that should be in the **install** section

2017-04-19 12:45 UTC, alan-hadyk commented on .gitignore
> +deploy-key
Well, `deploy-key` and `deploy-key.pub` should never be commited to repo, so this is to make sure that someone doesn't commit them by accident.

2017-04-19 12:49 UTC, alan-hadyk commented on gulpFunctions.js
> +    /TO_REPLACE_REDIR_URL=[^,]*/,
Those were done automatically on file save, but it's useful, because that's a removal of unnecessary white spaces.

2017-04-19 12:49 UTC, alan-hadyk commented on gulpFunctions.js
> +  chewie.preparePushResult(config, opt, (err) => {
It is required, otherwise plan will fail on `preparePushResult`

2017-04-19 14:10 UTC, akucharska commented on .travis.yml
> +- openssl aes-256-cbc -K $encrypted_321fb9daba18_key -iv $encrypted_321fb9daba18_iv -in deploy-key.enc -out deploy-key -d
Górnicki movie shows it in script :)

2017-04-19 14:14 UTC, sdomagala commented on .travis.yml
> +- export RESULT_LOC='git@github.com:YaaS/chewie-sample-result.git'
Please don't export it like this 😄

2017-04-19 14:15 UTC, alan-hadyk commented on .travis.yml
> +- export RESULT_LOC='git@github.com:YaaS/chewie-sample-result.git'
Why? What's wrong with that export? ;)

2017-04-19 14:20 UTC, sdomagala commented on .travis.yml
> +- export RESULT_LOC='git@github.com:YaaS/chewie-sample-result.git'
There is special field in .travis.yml to export env variables, `env -> global` I believe

2017-04-24 10:24 UTC, przezor commented on .gitignore
> +deploy-key
You are right. Still you do not add ssh-key to .gitignore. You should do it if you did it with deploy-key. For me it can stay.

2017-04-24 10:24 UTC, przezor commented on gulpFunctions.js
> +    /TO_REPLACE_REDIR_URL=[^,]*/,
(facepalm)

2017-04-24 10:24 UTC, przezor approved these changes

2017-04-25 08:15 UTC, merged